
```{r}
library(ggplot2)
n = 300
x = runif(n, -3, 3)
good_f = function(t){
  2 + (t-1)^2
}
y = good_f(x)  + rnorm(n, 0, 0.4)
mod = lm(y ~ x)
coef(mod)
main_plot = ggplot(data.frame(x = x, y = y), aes(x = x, y = y)) + geom_point() 
ggsave("curvy.pdf")
main_plot + geom_abline(intercept = coef(mod)[1], slope = coef(mod)[2])
ggsave("curvyline.pdf")

bad_f = function(t){
  1.5 + (t-1.5)^2
}

main_plot + stat_function(fun = bad_f)
ggsave("curvybadcurve.pdf")

main_plot + stat_function(fun = good_f)
ggsave("curvygoodcurve.pdf")

```



```{r}
Xy_simple = data.frame(
 response = factor(c(0, 0, 0, 1, 1, 1, 0, 0, 0)), #nominal
 first_feature =   c(1, 1, 2, 5, 6, 5, 1, 3, 2),    #continuous
 second_feature =  c(1, 2, 1, 5, 4, 4, 3, 1, 2)    #continuous
)

simple_viz_obj = ggplot(Xy_simple, aes(x = first_feature, y = second_feature)) + 
  geom_point(size = 5, aes(shape = response)) + xlab("") + ylab("")
simple_viz_obj

ggsave("linsep.pdf")
```


```{r}
Xy_simple = data.frame(
 response = factor(c(0, 0, 0, 1, 1, 1, 0, 0, 0, 0)), #nominal
 first_feature =   c(1, 1, 2, 5, 6, 5, 1, 3, 2, 5.2),    #continuous
 second_feature =  c(1, 2, 1, 5, 4, 4, 3, 1, 2, 4.2)    #continuous
)

simple_viz_obj = ggplot(Xy_simple, aes(x = first_feature, y = second_feature)) + 
  geom_point(size = 5, aes(shape = response)) + xlab("") + ylab("")
simple_viz_obj

ggsave("nonlinsep.pdf")
```



```{r}
boston = MASS::Boston
boston$chas = factor(boston$chas, labels = c("NOT_ON_RIVER", "ON_RIVER"))
boston$rad = factor(boston$rad, ordered = TRUE)
boston = boston[, c("chas", "rad", "rm", "medv")]
boston
```





